version: '3.8'

services:
  events-store:
    build: ./
    command: ./start.sh db ./events-store
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    restart: always
    image: clickhouse/clickhouse-server
    ports:
      - "9001:9000"
    volumes:
      - ./.database/clickhouse/data:/var/lib/clickhouse
  
